### ISSUE TITLE
Problem with ztanesh on OSX Mountain Lion (touch -d options don't exist on OSX)

### ISSUE THREAD

**Issue by ygbr** [miohtama/ztanesh#3]
Hi, I'm getting the following on every session start:

Last login: Mon Oct  8 07:47:04 on ttys003
/Users/yg/.zsh/var/compiled/allrcs:122: command not found: dircolors
touch: illegal option -- d
usage:
touch [-A [-][[hh]mm]SS] [-acfhm] [-r file] [-t [[CC]YY]MMDDhhmm[.SS]] file ...
Checking updates for RC files
Updating ~/tools
Already up-to-date.
/Users/yg/.zsh/var/compiled/allrcs:122: command not found: dircolors
touch: illegal option -- d
usage:
touch [-A [-][[hh]mm]SS] [-acfhm] [-r file] [-t [[CC]YY]MMDDhhmm[.SS]] file ...
Checking updates for RC files
Updating ~/tools
Already up-to-date.
/Users/yg/.zsh/var/compiled/allrcs:122: command not found: dircolors
touch: illegal option -- d
usage:
touch [-A [-][[hh]mm]SS] [-acfhm] [-r file] [-t [[CC]YY]MMDDhhmm[.SS]] file ...

This is due to the dact that the touch command on OSX only supports -t and not the -d option.
Also dircolors don't exist on ML so you can change that to gdircolors.

In order to fix it, you can do the following:

Edit .zsh/var/compiled/allrcs

on line _283_, change:

From:

```
touch -d "today 00:00" $TEMPFILE 
```

To:

```
touch -t `date +%m%d0000` $TEMPFILE
```

on line _287_, change:

From:

```
touch -d yesterday ~/.zsh/var/run/last_updated
```

To:

```
touch -t `printf "%s%02d0000" \`date +%m\` $((\`date +%d\`-1))` ~/.zsh/var/run/last_updated
```

on line _122_, change:

From:

```
eval `dircolors ~/.zsh/etc/dircolors` 2>&1 > /dev/null
```

To:

```
eval `gdircolors ~/.zsh/etc/dircolors` 2>&1 > /dev/null
```

This solves all issues on OSX Mountain Lion (10.8).

**Comment by elnygren** [comment]
Starting zsh on OS X 10.10.2:

```
/Users/censored/.zsh//lib/ztanesh-rcs.zsh:139: command not found: dircolors
touch: illegal option -- d
usage:
touch [-A [-][[hh]mm]SS] [-acfhm] [-r file] [-t [[CC]YY]MMDDhhmm[.SS]] file ...
Checking updates for RC files
Updating ~/tools
Already up-to-date.
/Users/censored/.zsh//lib/ztanesh-rcs.zsh:139: command not found: dircolors
touch: illegal option -- d
usage:
touch [-A [-][[hh]mm]SS] [-acfhm] [-r file] [-t [[CC]YY]MMDDhhmm[.SS]] file ...
Checking updates for RC files
Updating ~/tools
Already up-to-date.
/Users/censored/.zsh//lib/ztanesh-rcs.zsh:139: command not found: dircolors
touch: illegal option -- d
usage:
touch [-A [-][[hh]mm]SS] [-acfhm] [-r file] [-t [[CC]YY]MMDDhhmm[.SS]] file ...
```

Installed with
```brew install zsh coreutils lesspipe findutils highlight
git clone git://github.com/miohtama/ztanesh.git ~/tools
~/tools/zsh-scripts/setup.zsh```

```
which dircolors
# dircolors not found

which gdircolors
# /usr/local/bin/gdircolors
```
